---
# yamllint disable rule:line-length
version: '3'

tasks:
  build:
    desc: Builds a binary and docker image
    deps: [build-binary]
    cmds:
      - docker build . -t depode/dht

  build-binary:
    desc: Creates a cross platform binary
    cmds:
      - pyinstaller __init__.py -y
        --onefile
        --hidden-import gitlab.v4.objects
        --name dht
      - staticx ./dist/dht ./dist/dht

  build-fat-binary:
    desc: Creates a faster to boot binary for use outside of server environments
    cmds:
      - pyinstaller __init__.py -y
        --hidden-import gitlab.v4.objects
        --name dht
        --distpath /opt/
      - echo -e '#!/bin/sh\n/opt/dht/dht $@' | sudo tee /usr/local/bin/dht

  release:
    desc: Creates a Github release
    deps: [build]
    cmds:
      - git tag --delete latest
      - git tag -a latest -m 'Latest build'
      - >
        github-release delete
        --user danihodovic
        --repo dht
        --tag latest
      - >
        github-release release
        --user danihodovic
        --repo dht
        --tag latest
        --name dht
        --description "DHT"
      - >
        github-release upload
        --user danihodovic
        --repo dht
        --tag latest
        --name dht
        --file ./dist/dht
      - docker push depode/dht
