---
# yamllint disable rule:line-length
version: '3'

tasks:
  build:
    desc: Builds a binary and docker image
    deps: [build-binary]
    cmds:
      - docker build . -t depode/dht

  build-binary:
    desc: Creates a cross platform binary
    cmds:
      - pyinstaller dht.onefile.spec
      - staticx ./dist/dht ./dist/dht

  build-musl-binary:
    cmds:
      - docker build -f Dockerfile.alpine -t dht-musl .
      - mkdir -p ./dist/musl
      - docker rm dht-musl || true
      - docker create --name=dht-musl dht-musl
      - docker cp dht-musl:/usr/local/bin/dht ./dist/musl/

  build-fat-binary:
    desc: Creates a faster to boot binary for use outside of server environments
    cmds:
      - pyinstaller main_cli.py -y
        --hidden-import gitlab.v4.objects
        --hidden-import llm.default_plugins
        --hidden-import llm.default_plugins.openai_models
        --hidden-import llm.default_plugins.default_tools
        --hidden-import mistral
        --collect-all=llm_mistral
        --exclude-module PyInstaller
        --name dht
        --distpath /opt/
      - sudo /opt/dht/dht install

  build-fat-binary-taskwarrior:
    desc: Creates a fat taskwarrior binary
    cmds:
      - pyinstaller tasktools.spec --distpath /opt/ --noconfirm --clean

  release:
    desc: Creates a Github release
    deps: [build, build-musl-binary]
    cmds:
      - git tag --delete latest
      - git tag -a latest -m 'Latest build'
      - >
        github-release delete
        --user danihodovic
        --repo dht
        --tag latest
      - >
        github-release release
        --user danihodovic
        --repo dht
        --tag latest
        --name dht
        --description "DHT"
      - >
        github-release upload
        --user danihodovic
        --repo dht
        --tag latest
        --name dht
        --file ./dist/dht
      - >
        github-release upload
        --user danihodovic
        --repo dht
        --tag latest
        --name dht.musl
        --file ./dist/musl/dht
      - docker push depode/dht
